# Generated by Django 4.2.1 on 2023-06-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID DE COMUNA')),
                ('nombre_comuna', models.CharField(max_length=50, verbose_name='NOMBRE DE LA COMUNA')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID DEL PRODUCTO')),
                ('titulo_producto', models.CharField(max_length=60, verbose_name='NOMBRE DEL PRODUCTO')),
                ('descripcion', models.CharField(max_length=300, verbose_name='DESCRIPCION DEL PRODUCTO')),
                ('imagen', models.ImageField(upload_to='img/imgGaleria')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioADM',
            fields=[
                ('id_usuario_adm', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID DEL USUARIO ADMINISTRADOR')),
                ('nombre_usuario_adm', models.CharField(max_length=20, verbose_name='NOMBRE DE USUARIO ADMINISTRADOR')),
                ('contrasena_adm', models.CharField(max_length=10, verbose_name='CONTRASEÑA DEL USUARIO ADMINISTRADOR')),
                ('re_contrasena_adm', models.CharField(max_length=10, verbose_name='CONTRASEÑA DEL USUARIO ADMINISTRADOR')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID DEL USUARIO')),
                ('nombre_real', models.CharField(max_length=32, verbose_name='NOMBRE REAL DEL USUARIO')),
                ('apellidos', models.CharField(max_length=60, verbose_name='APELLIDOS DEL USUARIO')),
                ('nombre_usuario', models.CharField(max_length=20, verbose_name='NOMBRE DE USUARIO')),
                ('contrasena', models.CharField(max_length=10, verbose_name='CONTRASEÑA DEL USUARIO')),
                ('re_contrasena', models.CharField(max_length=10, verbose_name='CONTRASEÑA DEL USUARIO')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT DEL USUARIO')),
                ('celular', models.IntegerField(verbose_name='NUMERO DE CONTACTO')),
                ('direccion', models.CharField(max_length=32, verbose_name='DOMICILIO DEL USUARIO')),
                ('correo', models.EmailField(max_length=254, verbose_name='CORREO')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyWebApp.comuna')),
            ],
        ),
    ]
