# Generated by Django 4.2.1 on 2023-06-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='id_comuna',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID DE COMUNA'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id_producto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID DEL PRODUCTO'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID DEL USUARIO'),
        ),
        migrations.AlterField(
            model_name='usuarioadm',
            name='id_usuario_adm',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID DEL USUARIO ADMINISTRADOR'),
        ),
    ]
