# Generated by Django 4.2.1 on 2023-06-02 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebApp', '0002_alter_comuna_id_comuna_alter_productos_id_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='comuna',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
    ]
