# Generated by Django 4.2.1 on 2023-06-02 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebApp', '0004_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False, verbose_name='ID DE COMUNA')),
                ('nombre_comuna', models.CharField(max_length=50, verbose_name='NOMBRE DE LA COMUNA')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID DEL USUARIO')),
                ('nombre_real', models.CharField(max_length=32, verbose_name='NOMBRE REAL DEL USUARIO')),
                ('apellidos', models.CharField(max_length=60, verbose_name='APELLIDOS DEL USUARIO')),
                ('nombre_usuario', models.CharField(max_length=20, verbose_name='NOMBRE DE USUARIO')),
                ('contrasena', models.CharField(max_length=10, verbose_name='CONTRASEÑA DEL USUARIO')),
                ('re_contrasena', models.CharField(max_length=10, verbose_name='CONTRASEÑA DEL USUARIO')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT DEL USUARIO')),
                ('celular', models.IntegerField(verbose_name='NUMERO DE CONTACTO')),
                ('direccion', models.CharField(max_length=32, verbose_name='DOMICILIO DEL USUARIO')),
                ('correo', models.EmailField(max_length=254, verbose_name='CORREO')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyWebApp.comuna')),
            ],
        ),
    ]
