# Generated by Django 4.2.1 on 2023-06-02 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebApp', '0005_comuna_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'ordering': ['-id_comuna']},
        ),
    ]
