# Generated by Django 4.2.1 on 2023-06-02 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebApp', '0006_alter_comuna_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID CATEGORIA')),
                ('nombre_categoria', models.CharField(max_length=20, verbose_name='NOMBRE CATEGORIA')),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.CharField(default='0', max_length=9, verbose_name='PRECIO'),
        ),
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='STOCK'),
        ),
        migrations.AddField(
            model_name='productos',
            name='usuarioProp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWebApp.usuario'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes', verbose_name='IMAGEN'),
        ),
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWebApp.categoriaproducto'),
        ),
    ]
