# Generated by Django 4.2.1 on 2023-06-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebApp', '0007_categoriaproducto_productos_precio_productos_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=60, verbose_name='DOMICILIO DEL USUARIO'),
        ),
    ]
