# Generated by Django 4.2.1 on 2023-06-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebApp', '0008_alter_comuna_options_alter_usuario_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes', verbose_name='IMAGEN'),
        ),
    ]
