# Generated by Django 4.2.1 on 2023-06-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebApp', '0013_alter_carrito_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='titulo_producto',
            field=models.CharField(max_length=60, null=True, verbose_name='NOMBRE DEL PRODUCTO'),
        ),
    ]
