# Generated by Django 4.2.1 on 2023-06-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebApp', '0014_alter_productos_titulo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='titulo_producto',
            field=models.CharField(default='', max_length=60, verbose_name='NOMBRE DEL PRODUCTO'),
        ),
    ]
