# Generated by Django 4.2.1 on 2023-06-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebApp', '0015_alter_productos_titulo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWebApp.usuario', verbose_name='USUARIO'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='titulo_producto',
            field=models.CharField(max_length=60, verbose_name='NOMBRE DEL PRODUCTO'),
        ),
    ]
