# Generated by Django 4.2.1 on 2023-06-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebApp', '0016_alter_carrito_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(default=0, null=True, verbose_name='STOCK SOLICITADO'),
        ),
    ]
