# Generated by Django 4.2.1 on 2023-07-13 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebApp', '0017_alter_carrito_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito_Valido',
            fields=[
                ('id_producto_carrito', models.AutoField(primary_key=True, serialize=False, verbose_name='CARRITO ID')),
                ('cantidad', models.IntegerField(default=0, null=True, verbose_name='STOCK SOLICITADO')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWebApp.productos', verbose_name='PRODUCTO')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWebApp.usuario', verbose_name='USUARIO')),
            ],
        ),
    ]
