/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_automovil;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;

/**
 *
 * @author SkyHell
 */
public class VentanaIngresoCamion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogin
     */
    @Override
    public Image getIconImage() {
        Image reValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icons8-business-48.png"));
        return reValue;
    }

    public VentanaIngresoCamion() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("LOGIN");
        setResizable(false);
        MENSAJE.setVisible(false);

        setIconImage(getIconImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogoFondo = new javax.swing.JLabel();
        patente = new javax.swing.JLabel();
        ingresoPatente = new javax.swing.JTextField();
        marca = new javax.swing.JLabel();
        tipoAuto = new javax.swing.JLabel();
        año = new javax.swing.JLabel();
        ingresoAño = new javax.swing.JTextField();
        combustible = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        ingresoPrecio = new javax.swing.JTextField();
        KM = new javax.swing.JLabel();
        ingresoCarga = new javax.swing.JTextField();
        HP = new javax.swing.JLabel();
        ingresoEjes = new javax.swing.JTextField();
        ingresarBoton = new javax.swing.JButton();
        MENSAJE = new javax.swing.JLabel();
        Marca = new javax.swing.JComboBox<>();
        tipoIngreso = new javax.swing.JComboBox<>();
        combustibleIngreso = new javax.swing.JComboBox<>();
        volverBoton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        auto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));

        LogoFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.jpg"))); // NOI18N

        patente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesAuto/patenteLogo.png"))); // NOI18N

        ingresoPatente.setBackground(new java.awt.Color(102, 102, 102));
        ingresoPatente.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        ingresoPatente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        marca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesAuto/marcaLogo.png"))); // NOI18N

        tipoAuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesAuto/tipoAutoLogo.png"))); // NOI18N

        año.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesAuto/añoLogo.png"))); // NOI18N

        ingresoAño.setBackground(new java.awt.Color(102, 102, 102));
        ingresoAño.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        ingresoAño.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        combustible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesAuto/combustibleLogo.png"))); // NOI18N

        precio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesAuto/precioLogo.png"))); // NOI18N

        ingresoPrecio.setBackground(new java.awt.Color(102, 102, 102));
        ingresoPrecio.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        ingresoPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        KM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/capacidadCargaLogo.png"))); // NOI18N

        ingresoCarga.setBackground(new java.awt.Color(102, 102, 102));
        ingresoCarga.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        ingresoCarga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        HP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/capacidadEjesLogo.png"))); // NOI18N

        ingresoEjes.setBackground(new java.awt.Color(102, 102, 102));
        ingresoEjes.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        ingresoEjes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        ingresarBoton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ingresarBoton.setText("INGRESAR");
        ingresarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBotonActionPerformed(evt);
            }
        });

        MENSAJE.setFont(new java.awt.Font("Niagara Solid", 1, 10)); // NOI18N
        MENSAJE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mensajeIngresoExitoso.png"))); // NOI18N

        Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BMW", "Chevrolet", "Suzuki", "Hyundai", "Nissan", "Chery", "Mercedes-Benz", "Toyota", "Kia" }));
        Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaActionPerformed(evt);
            }
        });

        tipoIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Camioneta", "Camion" }));

        combustibleIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bencina", "Petroleo", "Electrico" }));

        volverBoton.setText("VOLVER");
        volverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ingresarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volverBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoFondo)
                .addGap(157, 157, 157))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(patente)
                        .addGap(12, 12, 12)
                        .addComponent(ingresoPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(marca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(614, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(año)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ingresoAño, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(precio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ingresoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(KM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ingresoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(HP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ingresoEjes, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tipoAuto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(523, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(combustible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combustibleIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MENSAJE)
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(patente)
                                            .addComponent(ingresoPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(13, 13, 13)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(marca)
                                            .addComponent(Marca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ingresoAño, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(tipoIngreso)
                                                    .addComponent(tipoAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(6, 6, 6)
                                                .addComponent(año)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(combustibleIngreso)
                                            .addComponent(combustible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(precio))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(MENSAJE, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(ingresoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(KM))
                            .addComponent(ingresoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HP))
                    .addComponent(ingresoEjes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogoFondo)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ingresarBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(volverBoton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 807, 420));

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(102, 102, 102));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresarLogo.png"))); // NOI18N

        auto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        auto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/autoLogo.png"))); // NOI18N
        jMenu1.add(auto);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(102, 102, 102));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificarLogo.png"))); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(102, 102, 102));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarLogo.png"))); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(102, 102, 102));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mostrarLogo.png"))); // NOI18N
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBotonActionPerformed

        int anio = Integer.parseInt(ingresoAño.getText());
        int precio1 = Integer.parseInt(ingresoPrecio.getText());
        int marca1 = (Marca.getSelectedIndex() + 1);
        int tipoCombustible = (combustibleIngreso.getSelectedIndex() + 1);
        int tipoAutomovil = (tipoIngreso.getSelectedIndex() + 1);
        String patente1 = ingresoPatente.getText();
        int capacidadCarga = Integer.parseInt(ingresoCarga.getText());
        int cantidadEjes = Integer.parseInt(ingresoEjes.getText());

        Camion camion = new Camion(capacidadCarga, cantidadEjes, patente1, anio, tipoCombustible, precio1, tipoAutomovil, marca1);

        camion.agregar(camion);

        try {
            Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_automovil", "root", "");
            PreparedStatement ps = conexion.prepareStatement("insert into automovil values (?,?,?,?,?,?)");
            PreparedStatement ps1 = conexion.prepareStatement("insert into camion values (?,?,?)");

            for (Camion camionL : camion.listacamion) {
                //patente
                ps.setString(1, camionL.getPatente());
                ps1.setString(1, camionL.getPatente());

                //año
                ps.setInt(2, camionL.getAnio());
                //precio
                ps.setInt(3, camionL.getPrecio());
                //marca
                ps.setInt(4, camionL.getMarca());
                //tipo auto
                ps.setInt(5, camionL.getTipoAutomovil());
                //combustible
                ps.setInt(6, camionL.getCombustible());

                //carga
                ps1.setInt(2, camionL.getCapacidadCarga());

                //ejes
                ps1.setInt(3, camionL.getCantidadEjes());
            }

            ps.executeUpdate();
            ps1.executeUpdate();
            MENSAJE.setVisible(true);
            camion.eliminar();
        } catch (Exception e) {
        }

        ingresoPatente.setText("");
        ingresoAño.setText("");
        ingresoEjes.setText("");
        ingresoCarga.setText("");
        ingresoPrecio.setText("");
    }//GEN-LAST:event_ingresarBotonActionPerformed

    private void MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcaActionPerformed

    private void volverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBotonActionPerformed
        dispose();
        VentanaPrincipal vp = new VentanaPrincipal();
        vp.setVisible(true);
    }//GEN-LAST:event_volverBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HP;
    private javax.swing.JLabel KM;
    private javax.swing.JLabel LogoFondo;
    private javax.swing.JLabel MENSAJE;
    private javax.swing.JComboBox<String> Marca;
    private javax.swing.JMenuItem auto;
    private javax.swing.JLabel año;
    private javax.swing.JLabel combustible;
    private javax.swing.JComboBox<String> combustibleIngreso;
    private javax.swing.JButton ingresarBoton;
    private javax.swing.JTextField ingresoAño;
    private javax.swing.JTextField ingresoCarga;
    private javax.swing.JTextField ingresoEjes;
    private javax.swing.JTextField ingresoPatente;
    private javax.swing.JTextField ingresoPrecio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel marca;
    private javax.swing.JLabel patente;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel tipoAuto;
    private javax.swing.JComboBox<String> tipoIngreso;
    private javax.swing.JButton volverBoton;
    // End of variables declaration//GEN-END:variables
}
